version: '3.8'

networks:
  footbal-predictions:

services:
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: football-predictions
      POSTGRES_PASSWORD: football-predictions
      POSTGRES_DB: football-predictions
    ports:
      - "5666:5432"
    networks:
      - footbal-predictions

  php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/football-predictions
    depends_on:
      - database
    networks:
      - footbal-predictions

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/football-predictions
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - footbal-predictions